### ISSUE TITLE
"std::bind" and MSVC-2015

### ISSUE THREAD

**Issue by gvanem** [pothosware/pothos-gui#151]
PothosGui.exe used to compile and link fine with MSVC-2015, but from yesterday's Github, I've getting this:
```
GraphEditor/GraphEditorTopologyStats.cpp(66): error C2039: 'bind': is not a member of 'std'
f:\qt\56\5.6\msvc2015\include\qtcore\qarraydatapointer.h(208): note: see declaration of 'std'
```

A bit of studying the pre-processed output, I find that `<functional>` doesn't seems to get automatically included (as in gcc). So with this little patch it compiles fine:
```
--- a/GraphEditor/GraphState.hpp 2017-01-02 19:24:43
+++ b/GraphEditor/GraphState.hpp 2017-06-05 10:21:41
@@ -11,6 +11,7 @@
 #include <vector>
 #include <map>
 #include <cassert>
+#include <functional>
```

**Comment by guruofquality** [comment]
It could have been an implied include from a qt header. I added functional to a few other files that used bind: https://github.com/pothosware/pothos-gui/commit/3abcf2b7210183dbbb6f6cfe29d0b1a41cfc1832
